connector:
   address: https://tc76.bitrix24.ru/rest/
   ami:
      hostname: 192.168.53.1
      port: 5038
      username: connector
      password: sheg0Aew-Fooh2ine
      debug: true
   bitrix:
      api: https://ntechs.bitrix24.ru/rest/
      auth: https://oauth.bitrix.info/oauth/token/
      clientid: local.5ecafa5d6b70c4.03846860
      clientkey: rloCh58Yjv3hw2qrTHI6cU42X2ZhqIzu4Enb2sA749sfu2F1ex
      externallines:
         - number: 679606
           name: Сетевые технологии
           channel: Local/{0}@ntechs-phones
           context: ntechs-phones
           exten: "{0}"
           priority: 1
         - number: 679618
           name: ИнТехСнаб
           channel: Local/{0}@ntechs-phones
           context: ntechs-phones
           exten: "{0}"
           priority: 1
   rules:
      # --- incoming call ---
      - events:
         - name: "Newchannel"
         - name: "UserEvent"
           constraints:
             UserEvent: UEIncomingCall
         - name: "Join"
         - name: "AgentCalled"
        action:
           - method: telephony.externalcall.register
             params:
                USER_ID: $(Responsible(${Join(CallerIDNum)})) | 10
                PHONE_NUMBER: ${Join(CallerIDNum)}
                LINE_NUMBER: ${UserEvent[UserEvent=UEIncomingCall](ConnectedLineNum)}
                CRM_CREATE: 1
                TYPE: 2
                SHOW: 0
      - events:
         - name: "AgentRingNoAnswer"
        action:
           - method: telephony.externalcall.hide
             params:
                USER_ID: $(REST("user.get", "USER_ID", "UF_PHONE_INNER", $(Channel(${AgentCalled(DestinationChannel)}, "${Newchannel(CallerIDNum)}"))))
      - events:
         - name: "AgentCalled"
        action:
           - method: telephony.externalcall.show
             params:
                USER_ID: $(REST("user.get", "USER_ID", "UF_PHONE_INNER", $(Channel(${AgentCalled(DestinationChannel)}, "${Newchannel(CallerIDNum)}"))))
      - events:
         - name: "Newchannel"
         - name: "UserEvent"
           constraints:
             UserEvent: UEIncomingCall
         - name: "AgentCalled"
         - name: "AgentConnect"
         - name: "Hangup"
        action:
           - method: telephony.externalcall.hide
             params:
                USER_ID: $(REST("user.get", "USER_ID", "UF_PHONE_INNER", $(Channel(${AgentConnect(Channel)}, "${Newchannel(CallerIDNum)}"))))
           - method: telephony.externalcall.finish
             params:
                USER_ID: $(REST("user.get", "USER_ID", "UF_PHONE_INNER", $(Channel(${AgentConnect(Channel)}, "${Newchannel(CallerIDNum)}")))) | 1
                DURATION: $(Duration())
                STATUS_CODE: 200
                VOTE: ${UserEvent[UserEvent=UEAssessment](Assessment)}
           - method: telephony.externalcall.attachrecord
             params:
                FILENAME: ${UserEvent(Filename)}.mp3
                FILE_CONTENT: $(FileContents(/home/monitor/records/${UserEvent[UserEvent=MonitorFile](Index)}/${UserEvent[UserEvent=MonitorFile](Filename)}.mp3))
      - events:
         - name: "Newchannel"
         - name: "UserEvent"
           constraints:
             UserEvent: UEIncomingCall
         - name: "!AgentConnect"
         - name: "Hangup"
        action:
           - method: telephony.externalcall.hide
             params:
                USER_ID: $(REST("user.get", "USER_ID", "UF_PHONE_INNER", $(Channel(${AgentCalled(DestinationChannel)}, "${Newchannel(CallerIDNum)}"))))
           - method: telephony.externalcall.finish
             params:
                USER_ID: $(Responsible(${Hangup(CallerIDNum)})) | 10
                DURATION: $(Duration())
                STATUS_CODE: 304
      # --- outgoing call ---
      - events:
         - name: "Newchannel"
         - name: "UserEvent"
           constraints:
              UserEvent: OutgoingCall
         - name: "Dial"
           constraints:
              SubEvent: Begin
        action:
           - method: telephony.externalcall.register
             params:
                USER_ID: $(REST("user.get", "USER_ID", "UF_PHONE_INNER", ${Newchannel(CallerIDNum)}))
                PHONE_NUMBER: ${Dial(ConnectedLineNum)}
                TYPE: 1
      - events:
         - name: "Newchannel"
         - name: "UserEvent"
           constraints:
              UserEvent: OutgoingCall
         - name: "Dial"
           constraints:
              SubEvent: Begin
         - name: "Dial"
           constraints:
              SubEvent: End
              DialStatus: ANSWER
         - name: "Hangup"
        action:
           - method: telephony.externalcall.hide
             params:
                USER_ID: $(REST("user.get", "USER_ID", "UF_PHONE_INNER", ${Newchannel(CallerIDNum)}))
           - method: telephony.externalcall.finish
             params:
                USER_ID: $(REST("user.get", "USER_ID", "UF_PHONE_INNER", ${Newchannel(CallerIDNum)}))
                DURATION: $(Duration())
                STATUS_CODE: 200
           - method: telephony.externalcall.attachrecord
             params:
                FILENAME: ${UserEvent[UserEvent=MonitorFile](Filename)}.mp3
                FILE_CONTENT: $(FileContents(/Users/shadrinov/Downloads/records/${UserEvent[UserEvent=MonitorFile](Index)}/${UserEvent[UserEvent=MonitorFile](Filename)}.mp3))
      - events:
         - name: "Newchannel"
         - name: "UserEvent"
           constraints:
              UserEvent: OutgoingCall
         - name: "Dial"
           constraints:
              SubEvent: Begin
         - name: "!Dial"
           constraints:
              SubEvent: End
              DialStatus: ANSWER
         - name: "Hangup"
        action:
           - method: telephony.externalcall.hide
             params:
                USER_ID: $(REST("user.get", "USER_ID", "UF_PHONE_INNER", ${Newchannel(CallerIDNum)}))
           - method: telephony.externalcall.finish
             params:
                USER_ID: $(REST("user.get", "USER_ID", "UF_PHONE_INNER", ${Newchannel(CallerIDNum)}))
                DURATION: $(Duration())
                STATUS_CODE: 304
