connector:
   ami-config:
   rules:
      - events:
         - Join
         - AgentCalled
        action:
           type: rest
           url: https://devel.ntechs/vtiger.php
        data:
           channelId: ${Join(chanid)}
           callerid: ${Join()}
           agentcalled: ${AgentCalled(member)}
      - events:
         - AgentRingNoAnswer
         - AgentCalled
         - Leave
        action:
           type: rest
           url: https://devel.ntechs/vtiger.php
        data:
           channelId: ${Join(chanid)}
           callerid: ${Join()}
           agentcalled: ${AgentCalled(member)}
      - events:
         - RTCPReceived
         - RTCPSent
         - RTCPReceived
        action:
           type: rest
           url: https://devel.ntechs/vtiger.php
        data:
           channelId: ${Join(chanid)}
           callerid: ${Join()}
           agentcalled: ${AgentCalled(member)}
