connector:
   address: https://connector.ntechs.ru/rest/
   bitrix:
      api: https://ntechs.bitrix24.ru/rest/
      auth: https://oauth.bitrix.info/oauth/token/
      clientid: clientid
      clientkey: clientkey
      externallines:
         - number: 123456
           name: Физическое лицо
           channel: Local/{0}@phy-phones
           context: org-phones
           exten: "{0}"
           priority: 1
         - number: 654321
           name: Организация
           channel: Local/{0}@org-phones
           context: org-phones
           exten: "{0}"
           priority: 1
   rules:
      - events:
         - Join
        action:
           type: rest
           url: https://ntechs.bitrix24.ru/rest/telephony.externalcall.register
        data:
           channelId: ${Join(chanid)}
           callerid: ${Join()}
           agentcalled: ${AgentCalled(member)}
      - events:
         - AgentRingNoAnswer
         - AgentCalled
         - Leave
        action:
           type: rest
           url: https://devel.ntechs/vtiger.php
        data:
           channelId: ${Join(chanid)}
           callerid: ${Join()}
           agentcalled: ${AgentCalled(member)}
      - events:
         - RTCPReceived
         - RTCPSent
         - RTCPReceived
        action:
           type: rest
           url: https://devel.ntechs/vtiger.php
        data:
           channelId: ${Join(chanid)}
           callerid: ${Join()}
           agentcalled: ${AgentCalled(member)}
