connector:
   address: https://connector.ntechs.ru/api/
   debug: true
   ami:
      hostname: localhost
      port: 5038
      username: ntcrm
      password: secret
      debug: true
      eventlifetime: 1800
   bitrix:
      api: https://ntechs.bitrix24.ru/rest/
      auth: https://oauth.bitrix.info/oauth/token/
      clientid: clientid
      clientkey: clientkey
      externallines:
         - number: 123456
           name: Физическое лицо
           channel: Local/{0}@phy-phones
           context: org-phones
           exten: "{0}"
           priority: 1
         - number: 654321
           name: Организация
           channel: Local/{0}@org-phones
           context: org-phones
           exten: "{0}"
           priority: 1
   rules:
      - events:
         - name: Join
         - name: AgentCalled
        action:
           - method: telephony.externalcall.register
             params:
                USER_ID: $(REST("user.get", "USER_ID", "UF_PHONE_INNER", $(Channel(${AgentCalled(DestinationChannel)}, "${Newchannel(CallerIDNum)}"))))
                PHONE_NUMBER: ${Join(CallerIDNum)}
                TYPE: 2
      - events:
         - name: AgentCalled
         - name: AgentRingNoAnswer
        action:
           - method: telephony.externalcall.hide
      - events:
         - name: AgentRingNoAnswer
         - name: AgentCalled
        action:
           - method: telephony.externalcall.show
             params:
                USER_ID: $(REST("user.get", "USER_ID", "UF_PHONE_INNER", $(Channel(${AgentCalled(DestinationChannel)}, "${Newchannel(CallerIDNum)}"))))
      - events:
         - name: Join
         - name: AgentCalled
         - name: Hangup
        action:
           - method: telephony.externalcall.finish
