connector:
   address: https://ntechs.bitrix24.ru/rest/
   ami:
      hostname: localhost
      port: 5038
      username: ntcrm
      password: secret
      debug: false
   bitrix:
      api: https://ntechs.bitrix24.ru/rest/
      auth: https://oauth.bitrix.info/oauth/token/
      clientid: clientid
      clientkey: clientkey
      externallines:
         - number: 123456
           name: Физическое лицо
           channel: Local/{0}@phy-phones
           context: org-phones
           exten: "{0}"
           priority: 1
         - number: 654321
           name: Организация
           channel: Local/{0}@org-phones
           context: org-phones
           exten: "{0}"
           priority: 1
   rules:
      - events:
         - name: "Newchannel"
         - name: "QueueCallerJoin"
         - name: "AgentCalled"
        action:
           - method: telephony.externalcall.register
             params:
                USER_ID: $(REST("user.get", "USER_ID", "UF_PHONE_INNER", ${AgentCalled(DestCallerIDNum)}))
                PHONE_NUMBER: ${QueueCallerJoin(CallerIDNum)}
                CRM_CREATE: 1
                TYPE: 2
                SHOW: 0
      - events:
         - name: "AgentRingNoAnswer"
        action:
           - method: telephony.externalcall.hide
             params:
                USER_ID: $(REST("user.get", "USER_ID", "UF_PHONE_INNER", ${AgentRingNoAnswer(DestCallerIDNum)}))
      - events:
         - name: "AgentCalled"
        action:
           - method: telephony.externalcall.show
             params:
                USER_ID: $(REST("user.get", "USER_ID", "UF_PHONE_INNER", ${AgentCalled(DestCallerIDNum)}))
      - events:
         - name: "Newchannel"
         - name: "QueueCallerJoin"
         - name: "AgentCalled"
         - name: "AgentConnect"
         - name: "AgentComplete"
         - name: "Hangup"
        action:
           - method: telephony.externalcall.finish
             params:
                USER_ID: $(REST("user.get", "USER_ID", "UF_PHONE_INNER", ${AgentComplete(ConnectedLineNum)}))
                DURATION: $(Duration(AgentConnect, AgentComplete))
                STATUS_CODE: 200
           - method: telephony.externalcall.attachrecord
             params:
                FILENAME: ${UserEvent(Filename)}.mp3
                FILE_CONTENT: $(FileContents(/home/monitor/records/${UserEvent[UserEvent=MonitorFile](Index)}/${UserEvent[UserEvent=MonitorFile](Filename)}.mp3))
      - events:
         - name: "Newchannel"
         - name: "QueueCallerJoin"
         - name: "!AgentConnect"
         - name: "!AgentComplete"
         - name: "Hangup"
        action:
           - method: telephony.externalcall.finish
             params:
                USER_ID: $(REST("user.get", "USER_ID", "UF_PHONE_INNER", ${AgentCalled(DestCallerIDNum)}))
                STATUS_CODE: 304
      - events:
         - name: "Newchannel"
         - name: "UserEvent"
           constraints:
              UserEvent: ExternalCall
         - name: "DialBegin"
        action:
           - method: telephony.externalcall.register
             params:
                USER_ID: $(REST("user.get", "USER_ID", "UF_PHONE_INNER", ${UserEvent[UserEvent=ExternalCall](CallerIDNum)}))
                PHONE_NUMBER: ${UserEvent[UserEvent=ExternalCall](ConnectedLineNum)}
                TYPE: 1
      - events:
         - name: "Newchannel"
         - name: "UserEvent"
           constraints:
              UserEvent: ExternalCall
         - name: "DialBegin"
         - name: "DialEnd"
           constraints:
              DialStatus: ANSWER
         - name: "Hangup"
        action:
           - method: telephony.externalcall.finish
             params:
                USER_ID: $(REST("user.get", "USER_ID", "UF_PHONE_INNER", ${UserEvent[UserEvent=ExternalCall](CallerIDNum)}))
                DURATION: $(Duration(DialEnd, Hangup))
                STATUS_CODE: 200
           - method: telephony.externalcall.attachrecord
             params:
                FILENAME: ${UserEvent[UserEvent=MonitorFile](Filename)}.mp3
                FILE_CONTENT: $(FileContents(/home/monitor/records/${UserEvent[UserEvent=MonitorFile](Index)}/${UserEvent[UserEvent=MonitorFile](Filename)}.mp3))
      - events:
         - name: "Newchannel"
         - name: "UserEvent"
           constraints:
              UserEvent: ExternalCall
         - name: "DialBegin"
         - name: "!DialEnd"
           constraints:
              DialStatus: ANSWER
         - name: "Hangup"
        action:
           - method: telephony.externalcall.finish
             params:
                USER_ID: $(REST("user.get", "USER_ID", "UF_PHONE_INNER", ${UserEvent[UserEvent=ExternalCall](CallerIDNum)}))
                STATUS_CODE: 304
