connector:
   ami-config:
   bitrix:
      api: https://ntechs.bitrix24.ru/rest/telephony.externalLine.get
      clientid: clientid
      clientkey: clientkey
   rules:
      - events:
         - Join
        action:
           type: rest
           url: https://ntechs.bitrix24.ru/rest/telephony.externalcall.register
        data:
           channelId: ${Join(chanid)}
           callerid: ${Join()}
           agentcalled: ${AgentCalled(member)}
      - events:
         - AgentRingNoAnswer
         - AgentCalled
         - Leave
        action:
           type: rest
           url: https://devel.ntechs/vtiger.php
        data:
           channelId: ${Join(chanid)}
           callerid: ${Join()}
           agentcalled: ${AgentCalled(member)}
      - events:
         - RTCPReceived
         - RTCPSent
         - RTCPReceived
        action:
           type: rest
           url: https://devel.ntechs/vtiger.php
        data:
           channelId: ${Join(chanid)}
           callerid: ${Join()}
           agentcalled: ${AgentCalled(member)}
